#!/usr/bin/env bash

ARGUMENTS=(
    "--nostdinc" # No C/C++ stuff
    "-I/usr/include/bash/"
    "-x" # Enable #exec macro
)

MODE=(
    -n -U "" # Macro start
          "" # Macro end without arguments
          "{" # Argument start sequence
          "\b" # Spaces (or tabs) instead of commas for separating arguments
          "}" # Argument end sequence
          "(" # List of chars to stack for argument balancing
          ")" # List of characters to unstack
          "$" # String to be used to refer to argument by number
          "" # Quote character
    -M "\n#\w" "\n" " " " " "\n" "" ""
    +ccss "#\b" "\n" +ccii "\\\n" ""
    +s '"' '"' '\' +s "'" "'" '\'
)

if ! command -v gpp &>/dev/null; then
    echo >&2 ":: Could not find \`gpp\` command"
fi

VERSION=0.0.0
while getopts 'v:o:n:' OPTION; do case "${OPTION}" in
        v) VERSION="${OPTARG}" ;;
        n) INFILE="${OPTARG}" ;;
        o) OUTFILE="${OPTARG}" ;;
        ?) exit 2 ;;
    esac
done
shift $((OPTIND - 1))

if [[ "${1}" == "--" ]]; then
    shift
fi

gpp "${ARGUMENTS[@]}" "${@}" "${MODE[@]}" "$INFILE" -o "$OUTFILE" -DCLAM_VERSION="${VERSION}"
